<?php
require_once __DIR__ . '/../models/product/Game.php';

$rawGamesList = [
    [
        'name' => 'Palla con Campana Interna',
        'img' => 'https://shop-cdn-m.mediazs.com/bilder/palla/gioco/in/vimini/karlie/con/topolino/sonoro/3/400/213597_pla_karlie_weidenball_mit_soundchipmaus_hs1_3.jpg',
        'price' => 5,
        'category' => 'cat',
        'material' => 'plastica',
        'color' => 'beige',
        'resistant' => true,
        'noise' => false,
    ],
    [
        'name' => 'Tunnel Pieghevole per Gatti',
        'img' => 'https://shop-cdn-m.mediazs.com/bilder/tunnel/gioco/per/gatti/tiaki/corduroy/3/400/351496_corduroy_cat_tunnel_fg_9519_3.jpg',
        'price' => 10,
        'category' => 'cat',
        'material' => 'stoffa',
        'color' => 'rosa',
        'resistant' => false,
        'noise' => false,
    ],
    [
        'name' => 'Palla Rimbalzante per Cani',
        'img' => 'https://shop-cdn-m.mediazs.com/bilder/gioco/per/cani/tiaki/palla/meteorite/5/400/307696_pla_leckerli_ball_meteorit_fg_4797_5.jpg',
        'price' => 8,
        'category' => 'dog',
        'material' => 'gomma',
        'color' => 'blu',
        'resistant' => true,
        'noise' => true,
    ],
    [
        'name' => 'Frisbee Volante per Cani',
        'img' => 'https://shop-cdn-m.mediazs.com/bilder/kong/flyer/2/400/26785_pla_kong_flyer_hundefrisbee_l_hs01_kf3e_2.jpg',
        'price' => 12,
        'category' => 'dog',
        'material' => 'plastica',
        'color' => 'rosso',
        'resistant' => true,
        'noise' => false,
    ],
    [
        'name' => 'Osso per Masticare per Cani',
        'img' => 'https://shop-cdn-m.mediazs.com/bilder/gioco/per/cani/osso/in/tpr/con/corda/2/400/69374_pla_hundespielzeug_tpr_knochen_mit_tau_fg_3382_2.jpg',
        'price' => 6,
        'category' => 'dog',
        'material' => 'gomma',
        'color' => 'verde',
        'resistant' => true,
        'noise' => false,
    ],
];
