<?php
require_once __DIR__ . '/../models/product/PetBed.php';

$rawPetBedsList = [
    [
        'name' => 'Cuscino Morbido per Gatti',
        'img' => 'https://shop-cdn-m.mediazs.com/bilder/lettocuscino/branca/2/400/24523_PLA_Kuschelbett_Branca_Two_in_One_HS_2.jpg',
        'price' => 15,
        'category' => 'cat',
        'material' => 'tessuto',
        'color' => 'marrone',
        'comfort' => true,
        'easyCleaning' => true,
        'shape' => 'circolare',
    ],
    [
        'name' => 'Cuccia con Tetto per Gatti',
        'img' => 'https://shop-cdn-m.mediazs.com/bilder/cuccia/per/cani/e/gatti/hafenbande/cottage/5/400/160196_pla_hafenbande_cottage_s_hs11_5.jpg',
        'price' => 25,
        'category' => 'cat',
        'material' => 'plastica',
        'color' => 'verde',
        'comfort' => true,
        'easyCleaning' => false,
        'shape' => 'rettangolare',
    ],
    [
        'name' => 'Cuscino Comodo per Gatti',
        'img' => 'https://shop-cdn-m.mediazs.com/bilder/letto/manila/7/400/235399_pla_hundebett_manila_fg_0263_7.jpg',
        'price' => 20,
        'category' => 'cat',
        'material' => 'tessuto',
        'color' => 'rosa',
        'comfort' => true,
        'easyCleaning' => true,
        'shape' => 'circolare',
    ],
    [
        'name' => 'Cuscino per Cani',
        'img' => 'https://shop-cdn-m.mediazs.com/bilder/cuscino/per/trasportini/per/cani/5/400/56825_PLA_Kuschelkissen_fuer_Hundeboxen_L90_FG__1_5.jpg',
        'price' => 35,
        'category' => 'dog',
        'material' => 'tessuto',
        'color' => 'grigio',
        'comfort' => true,
        'easyCleaning' => true,
        'shape' => 'rettangolare',
    ],
    [
        'name' => 'Cuccia con Coperta per Cani',
        'img' => 'https://shop-cdn-m.mediazs.com/bilder/cucciabaita/trixie/natura/lodge/con/terrazza/8/400/106396_pla_trixie_huette_lodge_mit_terrasse_hs_02_8.jpg',
        'price' => 30,
        'category' => 'dog',
        'material' => 'stoffa',
        'color' => 'marrone',
        'comfort' => false,
        'easyCleaning' => true,
        'shape' => 'rettangolare',
    ],
];
